

services:
  apache:
    image: httpd:latest
    ports:
      - "81:80"
    volumes:
      - ./vhosts/localhost.conf:/usr/local/apache2/conf/vhosts/localhost.conf:ro
      - ./vhosts/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./public:/usr/local/apache2/htdocs:ro
    depends_on:
      - php

  php:
    image: php:8.4-fpm
    volumes:
      - ./src:/usr/local/apache2/htdocs:ro


  composer:
    image: composer:latest
    volumes:
    - ./src:/app